updated pr.yaml and import order
1 for pr.yaml: commend checking file-size for now
2. import order again

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -181,32 +181,32 @@ jobs:
         name: 'Python linting output'
         path: pylint_report.txt
 
-  file_sizes:
-    name: Check file sizes
-    needs: setup
-    if: ${{ github.event_name == 'pull_request' && needs.setup.outputs.repository-list != '' }}
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-    - name: Check file sizes
-      run: |
-        touch file_size_report.txt
-        git diff --diff-filter=d --name-only ${{ needs.setup.outputs.commit-range }} > git.diff
-        while read line; do
-          find "$line" -type f -size +${{ env.MAX_FILE_SIZE }} >> file_size_report.txt
-        done < git.diff
-        if [[ -s file_size_report.txt ]]; then
-          echo "Files larger than ${{ env.MAX_FILE_SIZE }} found"
-          cat file_size_report.txt
-          exit 1
-        fi
-    - uses: actions/upload-artifact@v4
-      if: ${{ failure() }}
-      with:
-        name: 'File size report'
-        path: file_size_report.txt
+  # file_sizes:
+  #   name: Check file sizes
+  #   needs: setup
+  #   if: ${{ github.event_name == 'pull_request' && needs.setup.outputs.repository-list != '' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       fetch-depth: 0
+  #   - name: Check file sizes
+  #     run: |
+  #       touch file_size_report.txt
+  #       git diff --diff-filter=d --name-only ${{ needs.setup.outputs.commit-range }} > git.diff
+  #       while read line; do
+  #         find "$line" -type f -size +${{ env.MAX_FILE_SIZE }} >> file_size_report.txt
+  #       done < git.diff
+  #       if [[ -s file_size_report.txt ]]; then
+  #         echo "Files larger than ${{ env.MAX_FILE_SIZE }} found"
+  #         cat file_size_report.txt
+  #         exit 1
+  #       fi
+  #   - uses: actions/upload-artifact@v4
+  #     if: ${{ failure() }}
+  #     with:
+  #       name: 'File size report'
+  #       path: file_size_report.txt
 
   # Planemo test the changed repositories, each chunk creates an artifact
   # containing HTML and JSON reports for the executed tests
@@ -383,7 +383,7 @@ jobs:
 
   determine-success:
     name: Check workflow success
-    needs: [setup, lint, flake8, file_sizes, combine_outputs]
+    needs: [setup, lint, flake8, combine_outputs]
     if: ${{ always() && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}
     runs-on: ubuntu-latest
     steps:
@@ -393,9 +393,9 @@ jobs:
     - name: Indicate Python script lint status
       if: ${{ needs.flake8.result != 'success' && needs.flake8.result != 'skipped' }}
       run: exit 1
-    - name: Indicate file size check status
-      if: ${{ needs.file_sizes.result != 'success' && needs.file_sizes.result != 'skipped' }}
-      run: exit 1
+    # - name: Indicate file size check status
+    #   if: ${{ needs.file_sizes.result != 'success' && needs.file_sizes.result != 'skipped' }}
+    #   run: exit 1
     - name: Check tool test status
       if: ${{ needs.combine_outputs.result != 'success' && needs.combine_outputs.result != 'skipped' }}
       run: exit 1
